### ISSUE TITLE
Having a problem running the aplication

### ISSUE THREAD

**Issue by AbrilJara** [ResonantGeoData/Danesfield#109]
Hello, I have the following problem when i run docker `compose run --rm django ./manage.py migrate`.

`django.core.exceptions.ImproperlyConfigured: DEFAULT_FILE_STORAGE/STORAGES are mutually exclusive.`

I already commented the DEFAULT_FILE_STORAGE varaible in ../django/conf/global_settings.py but still having the same issue.

**Comment by Amr-Abdelaziz** [comment]
you are using new version of django. try to use version <4.2

**Comment by AbrilJara** [comment]
Thank you, I had to change the version in the setup.py to 4.1.2 to correspond with the requirment.txtr and it worked!

**Comment by ghost** [comment]
Hello, Can anyone please help resolve below initial setup error? Thanks

INFO: pip is looking at multiple versions of django-rgd-fmv[worker] to determine which version is compatible with other requirements. This could take a while.
ERROR: Could not find a version that satisfies the requirement kwiver; extra == "worker" (from django-rgd-fmv[worker]) (from versions: none)
ERROR: No matching distribution found for kwiver; extra == "worker"

**Comment by AbrilJara** [comment]
Hi, also need help. I tried following the step but every time I tried to execute something I got a different error so i gave up. Is there a chance to have the documentation updated?

**Comment by ghost** [comment]
Also, if i ignore the initial set up error above and run the app as follows: 

1. Run docker-compose up
2. In a seperate window, activate the virtual environment created previously in "Initial Setup" and run the following commands:
  source ./dev/export-env.sh
  celery --app danesfield.celery worker --loglevel INFO --heartbeat-interval 60

I get below errors:
1. FOR COMMAND 1. ABOVE:
(myenv2) PS C:\Users\Maan\Desktop\FT2404\Danesfield-main> deactivate
PS C:\Users\Maan\Desktop\FT2404\Danesfield-main> docker-compose up
time="2024-05-14T14:34:42+04:00" level=warning msg="C:\\Users\\Maan\\Desktop\\FT2404\\Danesfield-main\\docker-compose.yml: `version` is obsolete"
time="2024-05-14T14:34:42+04:00" level=warning msg="C:\\Users\\Maan\\Desktop\\FT2404\\Danesfield-main\\docker-compose.override.yml: `version` is obsolete"
[+] Building 272.2s (10/10) FINISHED                                                                                                   docker:default
 => [web internal] load build definition from web.Dockerfile                                                                                     0.1s
 => => transferring dockerfile: 220B                                                                                                             0.0s
 => [web internal] load metadata for docker.io/library/node:16                                                                                   4.2s
 => [web internal] load .dockerignore                                                                                                            0.0s
 => => transferring context: 2B                                                                                                                  0.0s
 => [web 1/5] FROM docker.io/library/node:16@sha256:f77a1aef2da8d83e45ec990f45df50f1a286c5fe8bbfb8c6e4246c6389705c0b                           265.9s
 => => resolve docker.io/library/node:16@sha256:f77a1aef2da8d83e45ec990f45df50f1a286c5fe8bbfb8c6e4246c6389705c0b                                 0.0s
 => => sha256:f77a1aef2da8d83e45ec990f45df50f1a286c5fe8bbfb8c6e4246c6389705c0b 776B / 776B                                                       0.0s
 => => sha256:1ddc7e4055fdb6f6bf31063b593befda814294f9f904b6ddfc21ab1513bafa8e 7.23kB / 7.23kB                                                   0.0s
 => => sha256:7e9bf114588c05b2df612b083b96582f3b8dbf51647aa6138a50d09d42df2454 17.58MB / 17.58MB                                                73.7s
 => => sha256:ffd9397e94b74abcb54e514f1430e00f604328d1f895eadbd482f08cc02444e5 51.89MB / 51.89MB                                               107.1s
 => => sha256:c94b82f9827cab6e421b350965a9ef11b25b13ffbd1030536203d541f55dcbe2 2.00kB / 2.00kB                                                   0.0s
 => => sha256:311da6c465ea1576925360eba391bcd32dece9be95960a0bc9ffcb25fe712017 50.50MB / 50.50MB                                               120.5s
 => => sha256:513d779256048c961239af5f500589330546b072775217272e19ffae1635e98e 191.90MB / 191.90MB                                             240.9s
 => => sha256:ae3b95bbaa61ce24cefdd89e7c74d6fbd7713b2bcae93af47063d06bd7e02172 4.20kB / 4.20kB                                                 108.7s
 => => sha256:0e421f66aff42bb069dffc26af6d132194b22a1082b08c5ef7cd69c627783c04 34.79MB / 34.79MB                                               153.5s
 => => sha256:ca266fd6192108b67fb57b74753a8c4ca5d8bd458baae3d4df7ce9f42dedcc1d 2.27MB / 2.27MB                                                 126.6s
 => => extracting sha256:311da6c465ea1576925360eba391bcd32dece9be95960a0bc9ffcb25fe712017                                                       10.0s
 => => sha256:ee7d78be1eb92caf6ae84fc3af736b23eca018d5dedc967ae5bdee6d7082403b 450B / 450B                                                     128.1s
 => => extracting sha256:7e9bf114588c05b2df612b083b96582f3b8dbf51647aa6138a50d09d42df2454                                                        2.1s
 => => extracting sha256:ffd9397e94b74abcb54e514f1430e00f604328d1f895eadbd482f08cc02444e5                                                       10.0s
 => => extracting sha256:513d779256048c961239af5f500589330546b072775217272e19ffae1635e98e                                                       19.5s
 => => extracting sha256:ae3b95bbaa61ce24cefdd89e7c74d6fbd7713b2bcae93af47063d06bd7e02172                                                        0.0s
 => => extracting sha256:0e421f66aff42bb069dffc26af6d132194b22a1082b08c5ef7cd69c627783c04                                                        3.6s
 => => extracting sha256:ca266fd6192108b67fb57b74753a8c4ca5d8bd458baae3d4df7ce9f42dedcc1d                                                        0.2s
 => => extracting sha256:ee7d78be1eb92caf6ae84fc3af736b23eca018d5dedc967ae5bdee6d7082403b                                                        0.0s
 => [web internal] load build context                                                                                                            0.3s
 => => transferring context: 526.75kB                                                                                                            0.3s
 => [web 2/5] COPY client/package*.json /opt/vue-project/                                                                                        0.6s
 => [web 3/5] COPY client/yarn.lock /opt/vue-project/                                                                                            0.0s
 => [web 4/5] RUN yarn                                                                                                                           0.9s
 => [web 5/5] WORKDIR /opt/vue-project                                                                                                           0.0s
 => [web] exporting to image                                                                                                                     0.2s
 => => exporting layers                                                                                                                          0.1s
 => => writing image sha256:3f34b54794fc7828fd9dca90d054d2de2b21b53c071be401c711916576680798                                                     0.0s
 => => naming to docker.io/library/danesfield-main-web                                                                                           0.0s
[+] Running 3/5
 ✔ Container danesfield-main-minio-1     Running                                                                                                 0.0s
 ✔ Container danesfield-main-postgres-1  Running                                                                                                 0.0s
 ✔ Container danesfield-main-rabbitmq-1  Running                                                                                                 0.0s
 - Container danesfield-main-django-1    Created                                                                                                 0.3s
 - Container danesfield-main-web-1       Created                                                                                                 0.3s
Attaching to django-1, minio-1, postgres-1, rabbitmq-1, web-1
yarn run v1.22.19
$ vue-cli-service serve
web-1       | /bin/sh: 1: vue-cli-service: not found
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
web-1 exited with code 127
django-1    | django-configurations version 2.5.1, using configuration DevelopmentConfiguration
django-1    | [10:39:22] INFO     Watching for file changes with             autoreload.py:677
django-1    |                     StatReloader
django-1    | Performing system checks...
django-1    |
django-1    | System check identified no issues (0 silenced).
django-1    | May 14, 2024 - 10:39:23
django-1    | Django version 4.1.2, using settings 'danesfield.settings'
django-1    | Starting development server at http://0.0.0.0:8000/
django-1    | Quit the server with CONTROL-C.

2. FOR COMMAND 2. ABOVE:
(myenv2) PS C:\Users\Maan\Desktop\FT2404\Danesfield-main> celery --app danesfield.celery worker --loglevel INFO --heartbeat-interval 60
Usage: celery [OPTIONS] COMMAND [ARGS]...
Try 'celery --help' for help.

Error: Invalid value for '-A' / '--app':
Unable to load celery application.
While trying to load the module danesfield.celery the following error occurred:
Traceback (most recent call last):
  File "C:\Users\ Maan\Desktop\FT2404\Danesfield-main\myenv2\lib\site-packages\celery\bin\celery.py", line 58, in convert
    return find_app(value)
  File "C:\Users\ Maan\Desktop\FT2404\Danesfield-main\myenv2\lib\site-packages\celery\app\utils.py", line 383, in find_app
    sym = symbol_by_name(app, imp=imp)
  File "C:\Users\ Maan\Desktop\FT2404\Danesfield-main\myenv2\lib\site-packages\kombu\utils\imports.py", line 59, in symbol_by_name
    module = imp(module_name, package=package, **kwargs)
  File "C:\Users\ Maan\Desktop\FT2404\Danesfield-main\myenv2\lib\site-packages\celery\utils\imports.py", line 109, in import_from_cwd
    return imp(module, package=package)
  File "C:\Users\Maan\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\ Maan\Desktop\FT2404\Danesfield-main\danesfield\__init__.py", line 4, in <module>
    from .celery import app as _celery_app  # noqa: F401
  File "C:\Users\Maan\Desktop\FT2404\Danesfield-main\danesfield\celery.py", line 4, in <module>
    import configurations.importer
ModuleNotFoundError: No module named 'configurations'

**Comment by ghost** [comment]
> Hi, also need help. I tried following the step but every time I tried to execute something I got a different error so i gave up. Is there a chance to have the documentation updated?

I had other difficulties but managed to clear those before reaching to above 3 errors. Not sure how to go about fixing these ones.
